minio:
  url: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: minioadmin

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 20MB
