server:
  port: 30004

spring:
  application:
    name: demo
  profiles:
    active: dev
#  config:
#    # use-legacy-processing: true
#    name: default
#    #location: 'classpath:/default.properties'
#    import: classpath:/default.properties

demo: demo
#spring:



---
spring:
  config:
    activate:
      on-profile: test
demo: test


---
spring:
  config:
    activate:
      on-profile: dev
demo: dev

---
spring:
  config:
    activate:
      on-profile: pro
demo: pro
