server:
  port: 20000
spring:
  application:
    name: yaml-profile

  profiles:
    active: test
demo: demo



---
spring:
  config:
    activate:
      on-profile: test
demo: test
---
spring:
  config:
    activate:
      on-profile: dev
demo: dev
---
spring:
  config:
    activate:
      on-profile: pro
demo: pro
