server:
  port: 10090

spring:
  application:
    name: swagger-aplication

  # ===== 自定义swagger配置 ===== #

swagger:
  enable: false
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}
  scans: '"com.noxus.draven.swagger.controller";"com.noxus.draven.swagger.contro"'
  author: draven
