spring:
  datasource:
    jndi-name: jndi/demo
    data-username: root
    data-password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

envs: linuxdeploy # localdeploy

server:
  port: 10088
