server:
  port: 8092
spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null  # 序列化时过滤为null的属性
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 116.196.77.250:8848
#  redis:
#    host: localhost
#  rabbitmq:
#    host: 106.54.238.192
#    username: gmall
#    password: gmall
#    virtual-host: /gmall

#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 10000
#        readTimeout: 10000

alipay:
  app_id: 2016091500518882
  merchant_private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC0d+/0p/Gw+isfrRO+d3ex1RKGzA00rJ07ttWhdNBTma4Q2sy0H4nR1B8zUsj5M4BA3/4WJvD2o/YrZ8yHjFr9m+TItvHz55dWH+B+muSEBHhQH485029Bl8sCslrJXXiZYCr/LO+0JVeKt8Byp2xoW1a6xw3UCFN89ZmK+iBFHkD8+Iio0EXrHbNDWXfnKefWkFcedHPqJGq+ICt40kTh+PlRbiSeNaUWKt5VzUBQQgu10PdJqPQ4OV/+NHoL/kssC7iSZWJ41JsjUHNY0EzPYzflxXMt22k2eHlKl8P6IkO9SqoN3H8JJXXN5joMv5ohlpxv9axwAeZWRQ5LvuBvAgMBAAECggEALXXtF2dbBebvCAq0Z412tHBlO1mZlgRJk2pKRGLFu9mBtLM5T8KGGDpkJayb/dKQY0dJnVDv8GF7OJHsPtUHcs1bg4g6SOO1Brf++EWSfQMXP6/Dh6CQbSiMtkAxiHooUBKeoisysuGZPNNvAjLUpzEjFuffvuLeDSNdK1o42NAKz3a4kCzB8OxJKfXrZ4sV1Y0QRQqDxAlicAL8zVa2gpQGyc7bDrf9zdvLZSH2MQUABqDiAmlwxEOX7gEDzK5fLqn095ILl4Z3cG8fFZFY4toClwcwDELGdVS6a31AzYCgnQyCL6qfJA6WSbFPOKcahUVMh4RzprpA+vDDWEEEwQKBgQDgpQlZrIleYgREieFPlaIGyF7TXnXHmZHi+CsmVZf2QO3KTtzvteDepJZ7rK0FVf1LQoLjE0NECpWaJOGO8K/LgbensM6JJFMm3BSNkqjKEDw2p+XLBinM5QgAvJYE/in0GphKDEpLsUtpkQVIkNd+P2puFXPhOlmFbjPA5J9XIQKBgQDNqGfjINovaf1JWXtMuJSmmdE4ingT9+sU7K+tUXH6gDEzSt1slUrD5yRgac55XIAgTZQg2IsyNNw6zoBHTHXPbmSSHw6+gpsuLI3Dzb71IvCF4qa3EMcThDSSimIhkGiruCQBIitNFtoWxyxyXFhzxQXWC7fBJJoSBV0cMyeVjwKBgFul2P+1rUFNObKAkeQ3Bqg/vLf89I4e7+6qEmiMSPfVG24K6IX/LKOIgEAqfVgM8c5vbxiW9j1fGBOP8lmvhfi/jh6iulAm+qmC5fuwFp6BKx+dNdmzRQBre+1ZAtc8nf8Rjom/I9xnk32ZBY/KT7AYzSHmLKV5eaY/BGwwmXUhAoGAXpPS6t4B2Qo6JFBVZsv/+LoGQKVVYYGDB8VtaRxqeVQYzEjimXvyvTMARKKEBMXoWnKy64QKR5WNrjGnRqLADxvqflRwGGbB7LMqouBssBlYWYoJN2ks1CnZb4baaCscJ9RwImFPXo1i0FTaeOFFAECcVXpgEB/ABweWcVCJJLsCgYAvQEnpgz89q2C+wSloPvqxtdWFs23FxUuPswMjAvyx3af0tB1SRFu0qyS/zpGuvMt/7aZjQfIYxzfKf6UryDlTGZUvXPFjbS/mKkGorUkh5MkTYzgsiQIFmUdkIH1ddknPeP9kk0pPmvYfhTwx5aZ4cJjXeVrcqRXBftyAjTD5ZQ==
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA14Mif6JjOaBsw31VlHTOPKeojISHOKRt7Uu9nJqHx4ot4mzzABxh2hyHGUI/0N/VH0ilJtKaXHLdC1xoIK5oBr9ugLt9hB755NvXPXBIm8D1z/wfJQd+FwHgOjXnz3CXL42BtJrq0YGcOjiJFHcF1MPwrdfzJQ3pyyLzyR2IHEDW7YBuceU6q1hIcTBQLRQBAO2RiUBpx7pQjNRfPXp2w6Tfy/5g2McZdC69xe5QHHOQ55Mbd3QG6UiYLTzkv6aBnwz4WJA5VAcRocY9HaXdNe7M2MGjrh/AlSkwpdH4bRHOewt48fTUwFoEZwESg9eNsRrRjHcew95oNIvtN66u+wIDAQAB
  return_url: http://draven.free-http.svipss.top/pay/alipay_callback
  notify_url: http://bynxbp.natappfree.cc/api/pay/alipay_callback
  sign_type: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do

#alipay:
#  app_id: 2021001146659470
#  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCnByW6oBDcBLs1JuagpS3ZE/C49txOUiHi/6m2E0jxANgHL3kcN505Wp1+VvsYvh0wTH8z/GA/UfU7wcACum/CAGis3UNGV+fg7LGv3RrNfGKRWaLR0h33sqn3fU9WkZIHmxcVtienZefOrjbMY09zvdjP+xxEgL6C8GzwRp8ODiDx9B3gy8JPg8cr5It4sWhO/llqKFMYVb4+H0OQ+AQMPf9EzZ6ArfK+RmtMjo0ohecVjBVSL29WLH0gw1J7Jy0M+xuT05FgABhtNgI18tjlFyyEmT4r5DiBEly1S81ib36KfUzE5n1ooIm31Jq/6COYTIj1MrRN2LAyayLkQQ0bAgMBAAECggEAaD+FxN1yqGArmBkXiNyPqRVRAaDSD/AjRlLb0dBnjkRAkPuIU5xCfTGZaulO/zppbWPRYNj8GYlFzm43MXy7lBI9Quc2vgjPqQsSO/l8aRRhUObpQJwsKBVTEC0d/6ILysN5vQtb5Jct/0ms2hSB2nN7hxPrqLXSMldtJuptC4+w/NIizLS14etBvtMBsy+M0P6uYcwaM0UIqvYQ0KURQBl67h3n7N0n1BCOQeilxXJTTV8l5zSYOwOE9jijZ5+8pRgtSnUZjCZqdaq9RpAVE1NQSYMQSJbIhIpLpCbmoWTtgZX9vWXlBwk6FHpeky3SZfhAyBvA8J5tdzsj2SOUgQKBgQDvuptKdr2UpquTGr8bnFjpJVLcutyaAlng+HIzUrQ10nEHy649B9h52X7M2S2NdjUk/QqGHTygfaXZCqmdn5lq181tPQeMPtU1eP9s/2QPLyRL0I+pBBE2GUmGVbGwBn2+/qBdTtoAclZEoyOadyno151HVzncK4Gk/y/mj57biQKBgQCyXVRScfghzUmJEfe4nxqphGwN4VlEOuObSC/4BKY6cQJSGXySBWTwZkEe3GEZ2B3VeV+K3HY9v/gL0Tije3PlhpwRKF5YVePMTCakhqI95fZCgb9rhpwTzvU/OfwUy6zCwpDiuPexzbIOBRefUSCHbw5xuwiPKDO1GNduEmWGgwKBgQCnHoiZbZOV6Gbdoxys696TkcBlPiMBfjgX/DroinQ0vSKs05IA29JOh4+80H3QCyLbSUen3QPhwhX261b5GkTCVfTQfWYgn8DUiShPXO7tIukDrT4pDjvNYe1+p4i6dJv+pNU4lvqkqxB2wt/UE9R0jLMJA8bDNNUpJ/jFm0OcOQKBgEBTHjzZc0YlddakDzWa04+8/QcIdRwBLOJsZzhH3PcImHCpVl6G6X81MVkC21XpteCt9AHtPgtI9xiz7Hww4nwtTo11hIjQ+OVNtUXydAJks6oKhtEta45NPe7+Z2XMilJ2vq+1S0bpSsR5m6pOJLATIh9r90tBkVxHSDIfGlQnAoGBAOYGKPdU0GetHXPnG+4CXlQ8Y1nJLotHF00+QmGMabTKiP/BQClk8zQU/FMT8ATfZbLXM3dGmpM4vadQZbN/dOXn51leZuipwGYGrGU973zXgtv0ye3TTSwtDYYfYbLp1Ddz83CiR3Uirw1dlUh4rjBz6iTV48ky8/W59bhSLaYY
#  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyMcoVYXVmPm9R4YwtrukXUvLIlCeBDaUAAe3OUnVk1dnF0GUSEsj/h3udeHRS/+Fvs/IS2EgkYbZoJznZF5p4sBBH3gU7CvVKT2HT0r+Di1FTBwS1szpXmc65ZJnJBypsmgK09cUJyprx5QOk6OdLAH/hrZ8ugQWW9wmYd2hT/zf7Ywq43JRuIfjYXX6XSbDcRF6ePg2payvCaQgX2kVYTi4fcthUedE/9Jjuz/b2qA3E744UBnj+husn6FKlCftQgYrLSka1EhStg+KJrBtvCVDMdsaeNE1mJyc+PPfuDHtusNFU1ASnTrAPO6uNFLS5eiHl2sn3AHW3j78OSeO3QIDAQAB
#  return_url: http://www.baidu.com
#  notify_url: xxx
#  sign_type: RSA2
#  charset: utf-8
#  gatewayUrl: https://openapi.alipay.com/gateway.do